In [3]:
import numpy as np

In [9]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])

In [25]:
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [26]:
a.shape

(2, 7)

In [27]:
#accessing 2 and 9 index column 1
a[:,1]

array([2, 9])

In [28]:
#accessing 2 alone. roll index 0 and column index 1
a[0,1]

2

In [30]:
#fetching 3 columns from both roll
a[:,2:5]

array([[ 3,  4,  5],
       [10, 11, 12]])

In [31]:
#fetching 3 columns from  roll 1 index 0
a[0,2:5]

array([3, 4, 5])

In [32]:
a.dtype

dtype('int32')

### 3Dimensional Array

In [33]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
b

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [34]:
b.shape

(2, 2, 2)

In [35]:
#access 4
b[0,1,1]

4

In [36]:
#accessing 3,4 and 7,8
b[:,1,:]

array([[3, 4],
       [7, 8]])

### Replacing value

In [42]:
#accessing 1,2 and 5,6 to -1,-2 and -5,-6

b[:,0,:] = ([-1,-2],[-5,-6])
b

array([[[-1, -2],
        [ 3,  4]],

       [[-5, -6],
        [ 7,  8]]])

### All 0s & 1s matrix

In [43]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [44]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [45]:
np.ones((3,2,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [53]:
# You can include the datatype you want
f = np.zeros((2,2,8), dtype="float")
f

array([[[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]]])

### Transpose

In [54]:
# Changing the shape of a matrix
f.T

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

### Any other numbers, instead of 0s and 1s

In [60]:
np.full((2,5), 13) # the full takes 2 arg. the size & the number you want

array([[13, 13, 13, 13, 13],
       [13, 13, 13, 13, 13]])

### To use a shape of already declared matrix to create our numbers

In [63]:
# we already have a delared
print(a)
a.shape

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


(2, 7)

In [64]:
#now let's create 23 number with the size of a(2,7)
np.full((a.shape), 23)

array([[23, 23, 23, 23, 23, 23, 23],
       [23, 23, 23, 23, 23, 23, 23]])

In [65]:
# Or using full_like
np.full_like(a, 23)

array([[23, 23, 23, 23, 23, 23, 23],
       [23, 23, 23, 23, 23, 23, 23]])

### Creating matrix of random decimal number

In [69]:
np.random.rand(2,4)

array([[0.42712275, 0.55681357, 0.31495291, 0.61483372],
       [0.41102036, 0.65662926, 0.189753  , 0.344859  ]])

### Creating matrix of random decimal number with already declared variable shape

In [72]:
print(a.shape)
np.random.random_sample(a.shape)

(2, 7)


array([[0.49734382, 0.05861993, 0.96929227, 0.28199595, 0.68090242,
        0.61879671, 0.2881239 ],
       [0.0186909 , 0.97653431, 0.42053403, 0.39051326, 0.78518688,
        0.31486225, 0.78053223]])

### Creating matrix of random Integer number

In [80]:
np.random.randint(1,4, size=(2,4)) #this gives us random numbers from 1 to 3. 4 won't be included

array([[1, 1, 1, 1],
       [1, 2, 3, 1]])

In [94]:
d = np.random.randint(5, size=(3,3), dtype="int32")
print(d.dtype)
print(d)

int32
[[4 4 2]
 [2 4 2]
 [1 3 1]]


## Random Normal Distribution

### Creating a football team

In [1]:
# This will give us random number, and will help us share between size of number specified

In [11]:
height = np.round(np.random.normal(1.91, 0.41, 50),2)
weight = np.round(np.random.normal(68.5, 23, 50),2)
height
weight

array([ 45.79,  70.56,  33.99,  66.56,  70.36,  49.57,  50.87,  38.86,
        64.1 ,  86.23,  60.65, 114.26,  59.23,  57.14,  90.74,  33.35,
        88.42,  77.46,  83.72,  87.02,  81.71,  79.78,  47.19,  72.92,
        56.85,  77.37,  74.22,  78.37,  64.27,  62.37,  38.78,  71.36,
        30.34,  26.74,  68.71,  72.76,  81.28,  76.04,  89.65,  56.44,
       107.91,  58.39,  79.3 ,  73.97,  41.99,  76.3 ,  56.16,  88.16,
        51.56,  46.74])

In [12]:
np_team = np.column_stack((height,weight))

np_team

np_team.shape

(50, 2)

In [19]:
mean_height = np.round(np.mean(np_team[:,0]),2)
mean_height

1.91

### Check the correlation between the weight and height of my team

In [21]:
np_team_corr = np.corrcoef(np_team[:,0], np_team[:,1])
np_team_corr

array([[1.        , 0.01877208],
       [0.01877208, 1.        ]])

### Class assignment

#### Create a player of 4000 and assign a random height and weight. 
### check mean, medean, correlation

In [26]:
team_height = np.round(np.random.normal(2.5, 1.34, 4000),3)
team_weight = np.round(np.random.normal(68.5, 34.3, 4000),3)

print(team_height)
print(team_weight)

[4.371 1.506 3.195 ... 1.606 4.227 2.506]
[ 63.652  49.085 -18.508 ... 100.709  66.456  48.725]


### Stack the height and weight together

In [28]:
team_stack = np.column_stack((team_height, team_weight))

In [29]:
team_stack

array([[  4.371,  63.652],
       [  1.506,  49.085],
       [  3.195, -18.508],
       ...,
       [  1.606, 100.709],
       [  4.227,  66.456],
       [  2.506,  48.725]])

In [33]:
team_stack[:,0]

array([4.371, 1.506, 3.195, ..., 1.606, 4.227, 2.506])

### Find the mean of the height & weight

In [44]:
mean_height = np.round(np.mean(team_stack[:, 0]),3)
mean_height

2.504

In [45]:
mean_weight = np.round(np.mean(team_stack[:,1]),3)
mean_weight

68.366

### Find the median of the height & weight

In [46]:
median_height = np.round(np.median(team_stack[:,0]),3)
median_height

2.501

In [47]:
median_weight = np.round(np.median(team_stack[:,1]),3)
median_weight

68.368

### Find the correlation between the height and weight

In [57]:
team_corr = np.corrcoef(team_stack[:,0], team_stack[:,1])
print(team_corr)
team_corr.shape

[[ 1.00000000e+00 -6.17711756e-04]
 [-6.17711756e-04  1.00000000e+00]]


(2, 2)

In [15]:
medean_height = np.median(np_team)
medean_height

14.809999999999999

In [84]:
c = np.random.randint(5, size=(3,3)) # this will give us random number from 0 to 4
c

array([[0, 0, 2],
       [4, 0, 0],
       [1, 0, 3]])

In [86]:
c[2,2]

3

### Accessment. Replicate this matrix without writing it manually

In [100]:
output = np.ones([5,5])
output

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [101]:
zeros = np.zeros([3,3])
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [102]:
zeros[1,1] = 9

In [103]:
zeros

array([[0., 0., 0.],
       [0., 9., 0.],
       [0., 0., 0.]])

In [104]:
output[1:4, 1:4] = zeros

In [105]:
output

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

### Be careful when copying arrays

In [111]:
## example of mistakes of copying normally
a = np.array([1,2,3])
print(a)
b = a
print(b)
b[0] = 100
print(b)

#we didn't touch a, but a is also affected immediately we modified b
print(a)

[1 2 3]
[1 2 3]
[100   2   3]
[100   2   3]


### Solution is to us Copy method

In [112]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100

print(a)
print(b)

[1 2 3]
[100   2   3]


## How to laod datas from file

In [116]:
from numpy import loadtxt

In [117]:
filename = 'pokemon_data.csv'

In [122]:
raw_data = open(filename, 'rb')

In [123]:
poke_man = loadtxt(raw_data, delimiter = ',')

ValueError: could not convert string to float: 'Bulbasaur'

## Dictionary